### ISSUE TITLE
 Licensing concerns

### ISSUE THREAD

**Issue by frankvandergrijn** [ki3v/xtramtest#1]
In your acknowledgement, you list Super PC/Turbo XT BIOS as "public domain" though earlier this year researchers were able to identify the origin of that project's copyrighted source code.  As you can see from the following links, the copyright on the code on which Super PC/Turbo XT is based is owned by IBM Corporation which should be acknowledged.

https://forum.vcfed.org/index.php?threads/anonymous-has-been-found.1246341/

https://forum.vcfed.org/index.php?threads/display-telecommunications-corporation-megaboard.63853/page-2#post-1361104

Hoogachtend
Frank van der Grijn

**Comment by ki3v** [comment]
Thank you for your comment.

I've skimmed through the discussion above (the first thread links to the second, so it's essentially the same discussion).

It's interesting, but I gather you're asking me to change attribution or change my acknowledgements to take the stance that the Super/Turbo XT BIOS is not public domain as it claims to be (which is presumably your position).

But from what I read, even if I assume what they found is correct (that parts or even most of the Super/Turbo XT BIOS are verbatim copies of the DTC BIOS and IBM acquired DTC's copyrights during settlement of a lawsuit) it does not establish that IBM owns the copyrights for the particular sequence (about 50 instructions) of code I used.

IBM obtained a settlement from DTC and acquired whatever copyrights DTC owned.  So far as I can tell, it was never established in court what DTC BIOS code actually infringed IBM's copyrights, or what copyrights DTC themselves actually owned.  Once IBM had DTC's copyrights, they could easily stop import of any clone using DTC's BIOS without actually proving anything else.

Copyright is complex.  One project, even one file, does not necessarily have one copyright owner.  Different parts of the file may be owned by different people.

The Super/Turbo XT BIOS has been publicly published since 2017, and no copyright owner has appeared to claim rights over it.  Perhaps that will change, or perhaps a consensus within the community will arise that the Super/Turbo XT is not actually in the public domain and its posting at http://www.phatcode.net will be taken down or its copyright status updated, but until that happens, I think your apparent request that I change this project's acknowledgements is at the very least premature.

As far as the particular sequence of code I used, I checked it against publicly-available copies of IBM's XT BIOS and it does not match.  So the sequence I used, at any rate, is not from the IBM BIOS, and it would not be appropriate for me to credit IBM for that code.  If anything, the research you refer to seems to make it even less clear to whom the credit or acknowledgement should go, if not to Jon Ρetrosky and Ya'akov Miles

As far as there being "Licensing concerns", even if IBM did hold copyright to the few instructions I used from the Super/Turbo BIOS, their use in this code would easily fall under the fair use exception to copyright, so I am not concerned about the license.

If anyone intends to assert that they own the copyright to the code in question, and is willing to document that ownership, they may open an issue here.
